### ISSUE TITLE
Map and Reduce code examples missing

### ISSUE THREAD

**Issue by frisina** [learn-co-curriculum/ruby-enumerables-introduction-to-map-and-reduce-lab#4]
Hey guys,
This section describe what map and reduce should do, but it doesn't what they are or how to implement them. It's a big ask to go from this to completing the lab without a bit more guidance.

**Comment by sgharms** [comment]
@frisina 

Can you explain further? As of commit 5e3a559, we have:

> we're going to produce a new Array after "transforming" or applying "work" to each element. An example would be "multiply each number in this Array by -1, returning a new Array of the input Array "negative-ized."

This would _seem_ to be an explanation and everything short of providing the code to the implementation.

What would ease this gap you noticed?

**Comment by sgharms** [comment]
I've attempted to implement your suggestion in the commit that i've marked as fixing this issue. If it still falls short, please re-open this and let us know what to add.

Thanks,

Steven
