### ISSUE TITLE
The 'tabular representation' is formatted incorrectly

### ISSUE THREAD

**Issue by taoliu12** [learn-co-curriculum/ruby-enumerables-introduction-to-map-and-reduce-lab#6]
In the instructions it reads:

Here's a tabular representation of reduce-ing an Array of [1, 2, 3] with a starting point of 0.

|Operation|Element 0|Element 1|Element2| |-|-|-|-| |Base Set|1|2|3| |Add to previous result function result|1|3|6|

Seems the HTML is badly formatted.

**Comment by sgharms** [comment]
These are showing correctly for us....

![image](https://user-images.githubusercontent.com/50019/60512117-bf9e4880-9ca1-11e9-8fad-1c07573edd6e.png)

@taoliu12 can you provide a screen-shot of what you're seeing?

**Comment by sgharms** [comment]
@taoliu12 OK, I got this to reproduce. Fixed as of 1da92fc
